default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

# Local development DB
development:
  <<: *default
  database: <%= ENV.fetch("DEV_DB_NAME") %>
  username: <%= ENV.fetch("DEV_DB_USER") %>
  password: <%= ENV.fetch("DEV_DB_PASSWORD") %>
  host: <%= ENV.fetch("DEV_DB_HOST") %>

# Local test DB
test:
  <<: *default
  database: <%= ENV.fetch("TEST_DB_NAME") %>
  username: <%= ENV.fetch("TEST_DB_USER") %>
  password: <%= ENV.fetch("TEST_DB_PASSWORD") %>
  host: <%= ENV.fetch("TEST_DB_HOST") %>

# Railway production DB
production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
