default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DEV_DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DEV_DB_USER", "postgres") %>
  password: <%= ENV.fetch("DEV_DB_PASSWORD", "0120852868") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: <%= ENV.fetch("DEV_DB_NAME", "blog_app_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("TEST_DB_NAME", "blog_app_test") %>

production:
  url: <%= ENV.fetch("DATABASE_URL") %>
