development:
  adapter: postgresql
  encoding: unicode
  database: blog_application_dev
  pool: 5
  username: postgres
  password: 0120852868

test:
  adapter: postgresql
  encoding: unicode
  database: blog_application_testing
  pool: 5
  username: postgres
  password: 0120852868

production:
  adapter: postgresql
  encoding: unicode
  database: blog_application_prod
  pool: 5
  username: postgres
  password: 0120852868