default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bolg_app_development
  username: postgres
  password: 0120852868
  host: localhost

test:
  <<: *default
  database: bolg_app_test
  username: postgres
  password: 0120852868
  host: localhost

production:
  <<: *default
  database: bolg_app_production
  username: postgres
  password: 0120852868
  host: localhost
